Rename openid_wallet_relying_party to openid_credential_verifier
peppelinux/federation-wallet pull request #15
Opened 2024-08-17 21:48 UTC by selfissued

Fixes #10 

Cc: @rohe @ve7jtb @vdzhuvinov

2024-08-17 21:50 UTC, peppelinux requested changes
only a quick fix on the metadata name, once you'll get it merged you can consider this PR approved and therefore merge it without any further revision by me

2024-08-17 21:50 UTC, peppelinux commented on openid-federation-wallet-1_0.md
> +This specification introduces a distinct Entity Type Identifier for the OpenID Credential Verifier to clearly differentiate it from a traditional OpenID Connect Relying Party (`openid_relying_party`)
```suggestion
This specification introduces a distinct Entity Type Identifier for the OpenID Credential Verifier to clearly differentiate it from a traditional OpenID Connect Relying Party (`openid_credential_verifier`). This distinction highlights the unique characteristics and functionalities of the Wallet ecosystem and its Credential Verifier.
```

2024-08-17 21:54 UTC, selfissued commented on openid-federation-wallet-1_0.md
> +This specification introduces a distinct Entity Type Identifier for the OpenID Credential Verifier to clearly differentiate it from a traditional OpenID Connect Relying Party (`openid_relying_party`)
This suggestion is wrong.  We're actually talking about an OpenID Connect RP here.

2024-08-17 21:58 UTC, peppelinux approved these changes

2024-08-18 20:01 UTC, rohe approved these changes

2024-08-18 20:24 UTC, merged

2024-08-18 23:06 UTC, ve7jtb reviewed
lgtm